#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace

source usr/bin/dist-installer-cli

set_target_user_account root

test_file -f /etc/hostname
test_file -d /
test_file -w "$HOME"
test_file -r /
test_file -e /

if ! test_file -f /nonexisting; then
   true OK
else
   exit 1
fi

test_run_as_target_user

true "$0: END"

